server:
  assets-path: /app/assets

theme:
  light: true
  background-color: 28 40 77
  primary-color: 155 100 20
  negative-color: 0 100 60
  contrast-multiplier: 1.1
  text-saturation-multiplier: 0.5
  custom-css-file: /assets/user.css

document:
  head: |
    <script src="/assets/clipboard-tailscale.js"></script>

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
  !include: homelab.yml
  !include: finance.yml
  #!include: entertainment.yml
  #!include: news.yml
